1️⃣ Load and Inspect Data  
→ Load the dataset into a Pandas DataFrame and display the first 5 rows.

In [1]:
import pandas as pd

df = pd.read_csv("cybersecurity_incidents.csv")

print(df.head(5))

  incident_id        date organization     attack_type  severity  \
0     INC1000  2023-04-13    CyberGrid      Ransomware    Medium
1     INC1001  2024-03-11   DataSecure        Phishing  Critical
2     INC1002  2023-09-28     BitGuard      Ransomware    Medium
3     INC1003  2023-04-17    CyberGrid  Insider Threat    Medium
4     INC1004  2023-03-13     BitGuard         Malware      High

   data_loss_gb  financial_impact_usd  region  detected_by  \
0          3.36              55657.21  Africa  SOC Analyst
1         21.22              71185.04  Europe  User Report
2          1.39              54370.83  Europe  SOC Analyst
3          5.58              19578.63    Asia          IDS
4          7.17              76233.68  Europe  SOC Analyst

   response_time_hours  resolved
0                 23.1     False
1                 70.5      True
2                 13.4      True
3                  2.2      True
4                 55.2      True

2️⃣ Filtering and Conditional Selection  
→ Find all incidents where severity is "Critical" and resolved is False.

In [2]:
df[(df["severity"] == "Critical") & (df["resolved"] == False)]

,incident_id,date,organization,attack_type,severity,data_loss_gb,financial_impact_usd,region,detected_by,response_time_hours,resolved
9,INC1009,2023-08-03,InfoTrust,Brute Force,Critical,5.02,21739.30,North America,IDS,4.4,False
37,INC1037,2023-07-09,CyberGrid,Phishing,Critical,0.49,37175.87,South America,Automated System,44.9,False
47,INC1047,2023-06-16,CyberTech,Phishing,Critical,5.14,76654.96,North America,IDS,67.5,False

3️⃣ Grouping and Aggregation  
→ Calculate the average financial impact per attack_type.

In [4]:
df.groupby("attack_type")["financial_impact_usd"].mean()

attack_type
Brute Force       50455.675833
DDoS              47747.806000
Insider Threat    43440.710000
Malware           72257.033333
Phishing          56603.575000
Ransomware        59219.802222
SQL Injection     61639.137500
Name: financial_impact_usd, dtype: float64

4️⃣ Sorting and Ranking  
→ List the top 5 incidents with the highest financial impact.

In [6]:
df.sort_values(
    by="financial_impact_usd",
    ascending=False
).head(5)

,incident_id,date,organization,attack_type,severity,data_loss_gb,financial_impact_usd,region,detected_by,response_time_hours,resolved
22,INC1022,2024-01-21,DataSecure,Ransomware,Medium,0.96,118360.55,Africa,IDS,46.2,False
41,INC1041,2023-09-01,CyberGrid,Malware,Medium,2.07,94073.44,South America,IDS,49.4,True
49,INC1049,2024-01-23,InfoShield,Insider Threat,Low,0.88,84550.12,South America,IDS,30.7,True
5,INC1005,2023-01-21,SecureWare,Brute Force,Medium,1.36,83127.64,North America,IDS,58.3,True
11,INC1011,2024-04-03,CyberTech,DDoS,High,0.47,81709.74,Africa,IDS,64.0,True

5️⃣ Advanced Filtering  
→ Display all incidents that occurred in "Asia" region  
   where attack_type is "Ransomware" and severity is "High".

In [8]:
print(
    df[
        (df["region"] == "Asia") &
        (df["attack_type"] == "Ransomware")
    ][["region", "attack_type", "severity"]]
)

   region attack_type severity
28   Asia  Ransomware   Medium